services:

  api:
    container_name: trubridge-ms-outcomes
    environment:
      - DEV_DB_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/trubridge-ms-outcomes-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:18.2-alpine3.22
    container_name: trubridge-ms-outcomes-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trubridge-ms-outcomes-db
    ports:
      - "5430:5432"