services:

  sql:
    container_name: trubridge-db
    build:
      context: db
      dockerfile: db.Dockerfile
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_DB=trubridge-ms-outcomes-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: trubridge-api
    environment:
      - DB_CONNECTION_STRING=postgresql://postgres:postgres@sql:5432/trubridge-ms-outcomes-db
    build:
      context: api
      dockerfile: api.Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - sql

  webapp:
    container_name: trubridge-webapp
    build:
      context: web
      dockerfile: web.Dockerfile
    ports:
      - "3010:80"
    depends_on:
      - api

  pgadmin:
    container_name: trubridge-pgadmin
    image: dpage/pgadmin4:9.12.0
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin_data:
